### PR TITLE
Allow usage of non-default copyManager in JacksonDeSerializer

### PR DESCRIPTION
**Pull request by martin-bpw**

### CODE REVIEW

**Comment by martin-bpw** [comment]
Draft proposal https://github.com/spdx/spdx-java-jackson-store/issues/75

**Comment by goneall** [comment]
Thanks @martin-bpw - I'll take a look later today - but the approach seems resonable.

**Review by goneall — COMMENTED** [review]
Looks like it is missing the import statement JacksonDeSerializer:

```
import org.spdx.core.IModelCopyManager;
```

and in the MultiFormatStore:

```
import org.spdx.library.ModelCopyManager;
```

**Review by goneall — APPROVED** [review]
LGTM - Thanks @martin-bpw

**Pull request merged**
